
name: Jobs from YAML
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  Run-Python-Script:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Install Requirements.txt
        run: pip install -r .github/requirements.txt
      - name: Run Python
        run: python .github/main.py
        env: 
          API_KEY: "${{secrets.API_KEY}}"